### ISSUE TITLE
Binaries not published for 0.1.18

### ISSUE THREAD

**Issue by ProjectInitiative** [ustaxes/UsTaxes#1012]
us-taxes_0.1.16_amd64.AppImage
![Screenshot from 2022-03-15 08-26-24](https://user-images.githubusercontent.com/6314611/158387914-95104f1b-8efe-4d8a-99a8-bede6a18560f.png)

**Comment by ProjectInitiative** [comment]
The current web version does not have this issue, however there is no provided 0.1.18 appimage available in releases.

**Comment by zakpatterson** [comment]
Thank you for letting us know. I'll see if I can push another release now. The binary releases are done manually whenever we think there is some new meaningful feature to share, and we are way behind because lately there have been many. 

Please join the discussion on discord!

**Comment by thegrims** [comment]
@zakpatterson Yeah, I think the latest versions of tauri/tauri build are broken but got automerged because the build check doesn't include tauri build aspects. I tried to fix this last week, but got sidetracked.

**Comment by zakpatterson** [comment]
Successfully released. https://github.com/ustaxes/UsTaxes/releases
