### ISSUE TITLE
Change bank routing number error message to suggest 9 digits rather than 10

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#105]
Routing numbers are 9 digits long, the error message should reflect that. Error messages should use 'digits' rather than 'numbers' for clarity.

![image](https://user-images.githubusercontent.com/8848557/108019634-80844e80-6fcf-11eb-8f18-8aae1bd82db4.png)

https://www.plainfinances.com/grow/routing-number/

**Comment by stevendaniels** [comment]
Should `digits` be used for all error messages in https://github.com/ustaxes/UsTaxes/blob/a0b1bb53fb274d6e8d12da458ed1d03cc3b7396c/src/components/Patterns.ts or just the routing number description?

**Comment by thegrims** [comment]
@stevendaniels digits should be used for all of the error descriptions in patterns.ts instead of numbers, good callout

**Comment by thegrims** [comment]
It appears that US bank account numbers can be 4-17 digits long https://stackoverflow.com/a/1540314/5853454
