### ISSUE TITLE
Can't complete W2: always get "data will be lost"

### ISSUE THREAD

**Issue by scandey** [ustaxes/UsTaxes#1051]
Every time I try to enter info into the W2 page and clock save+continue, I get:
```
Are you sure you want to leave? Data will be lost
```
If I choose cancel, the entire W2 screen reloads and loses everything immediately. If I choose OK, I continue to the 1099 page, but if I return to the W2 page, the entire W2 entry is gone. After replicating this a few times with fake inputs, I was able to continue and see that the W2 entry appeared to have been saved. However, when I continued on from there, I got a blank screen. 

Possibly relevant:
warnings in console from REHYDRATE about "Form submission canceled because form is not connected"

Type errors:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'A')
    at 75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1676849
    at Array.filter (<anonymous>)
    at jr (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1676813)
    at ua (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1118458)
    at Yu (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1170722)
    at As (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1157971)
    at Ps (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1157899)
    at Es (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1157762)
    at ys (75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1154728)
    at 75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1:1104255
lu @ 75d7af22d1f29da9ef0057b14fed542d0080aa71.js:1
```
Reloading from the blank white page works, but the W2 entry was not saved. 

Also possibly relevant: I originally attempted to use an '&' in the Occupation field, which probably is not acceptable, but was not highlighted as being incorrect until I accidentally attempted to include a "7". 

Browser: Chrome Version 99.0.4844.83 (Official Build) (x86_64)
OS: Mac OS 12.3

**Comment by thegrims** [comment]
Thanks for the report! On the job information page, there is a separate save button and a discard button in addition to the back and save and continue buttons. Did you press the save button before pressing the save and continue button on the page? The data is saved on a per-job basis, so the UI can be a little confusing
![image](https://user-images.githubusercontent.com/8848557/160326989-bec7c467-57a8-4c2c-b9f0-840f7e6afb54.png)

**Comment by scandey** [comment]
I'm pretty sure I initially tried "Save and Continue", but on later attempts I tried first just doing a "Save" without the continue. There is no error message after "Save", but pressing "Save and Continue" after that still triggered the warning (and failed to save  data either way). It is not impossible I managed to corrupt the saving system somehow on an initial attempt (ampersand character in employee field? the 12DD field existing?), so I will try clearing LocalStorage and tracking actions more closely later this week.

**Comment by scandey** [comment]
Can't reproduce when I tried tonight, so issue could be closed until/unless this rears its head again. 

Thinking back though, I bet I tried to Save And Continue without Save first, and that in combination with something else somehow ended up in a state where nothing related to the W2 was saving properly.
