### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by bradydowling** [ustaxes/UsTaxes#108]
It would be really helpful to have a landing page with blurbs about what this project does right now and what it doesn't do. Perhaps a feature-to-feature comparison table with other popular tax products and their different tiers.

Side note, there are many people that would love to bury other popular tax products so if you're serious about this then you might consider doing a gofundme or some kind of crowd funding to give you more time to work on it.

**Comment by thegrims** [comment]
Absolutely! I think this could be used in tandem with https://github.com/thegrims/UsTaxes/issues/97 to allow users to see if a tax form they need is not supported before they invest time in filling out the app

**Comment by eoncarlyle** [comment]
@thegrims I'll write a draft landing page addressing this on Saturday or Sunday, the supported income/credits/states in the README look like a good starting point

**Comment by thegrims** [comment]
Sounds great!
