### ISSUE TITLE
Schedule 8812

### ISSUE THREAD

**Issue by philiplantz** [ustaxes/UsTaxes#1093]
Schedule 8812 line 5 should be 0 if line 4a is 0.

Part I-B is blank, but I think that is a result of the first problem.  

Part III line 33 is 40,000. It should be 60,000 for married filing jointly.  
Line 34 should be line 3 minus line 33. Instead it is equal to line 3.

**Comment by philiplantz** [comment]
I don't have a way to build and test yet, so I'm just putting this here for safekeeping.

**Schedule8812.ts**
line 127 insert:
    if ((this.l4a() ?? 0) === 0) {
        return 0
    }

line 128 should be: l4b() * 3600

line 483 should be:
        if (fs === FilingStatus.MFJ || fs === FilingStatus.W)

line 492 should be:
      const l34 = Math.max(0, this.l3() - this.l33())

**Comment by zakpatterson** [comment]
Would you like to review the fix for this issue? 

Deploy preview is here: https://deploy-preview-1095--ustaxes.netlify.app/

I added a suggestion for importing your data into the preview in your other issue.

Thanks so much!

**Comment by philiplantz** [comment]
This fixes the problems in lines 5, 33, and 34.

Unfortunately I forgot to include the problem with line 10 in the original bug report.

Line 10 has the subtraction reversed. It should be line 3 minus line 9.
l10 = (): number => Math.max(0, nextMultipleOf1000(this.l3() - this.l9()))

**Comment by zakpatterson** [comment]
Good catch, updated.

**Comment by philiplantz** [comment]
Schedule 8812 now seems to be filled out correctly.
However, line 14h of schedule 8812 should be entered online 19 of form 1040, but line 19 is still blank.

**Comment by zakpatterson** [comment]
> Schedule 8812 now seems to be filled out correctly.
> However, line 14h of schedule 8812 should be entered online 19 of form 1040, but line 19 is still blank.

thank you so much for these clear issue reports!

**Comment by zakpatterson** [comment]
@philiplantz Since you were such a great help in reviewing Schedule 8812, would you like to review the advance child tax credits pull request: https://github.com/ustaxes/UsTaxes/pull/1112?

Aside from the impact of 2225 which we haven't started yet, this should be the last step for 8812.
