### ISSUE TITLE
Add auto release deployments of desktop application

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#114]
A lot of people in the hacker news chat were rightly worried about an unknown web site asking for their social details. Of course we know that data never leaves the user's machine but there's no obvious way for the user to know that. 

I think it would help if we had regular releases of the desktop application binaries.

**Comment by thegrims** [comment]
That absolutely makes sense

**Comment by zakpatterson** [comment]
Closed by #141
