### ISSUE TITLE
Add edit button for list forms

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#121]
The list component currently used for dependents, spouses, w2s and 1099s should support editing. 

Hover over a list item to get an edit button, open form and replace form content on click, overwrite state on save.

**Comment by wisefool769** [comment]
I'll take a stab at this

**Comment by zakpatterson** [comment]
> I'll take a stab at this

@wisefool769 That's awesome. Please come to the discord channel, I can assist if needed.

**Comment by jswiss** [comment]
I'm also happy to help on this, provided I'm not stepping on @wisefool769 's toes.

WRT edit button on hover, I believe screen readers struggle with modals so an 'edit on hover' approach would ding accessibility, so would it be ok to do an edit icon button next to the trash icon instead?

**Comment by zakpatterson** [comment]
@jswiss you're right, go for it!

**Comment by thegrims** [comment]
@zakpatterson Should we close this now? I think edit icons have been added to all list items
