### ISSUE TITLE
Should we move this repository into its own organization?

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#122]
I opened [github.com/ustaxes](//github.com/ustaxes), with myself and @thegrims as owners

https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#whats-transferred-with-a-repository

* Helps promote this project as its own independent thing
* I would like to be able to add a commit to #84 without superseding #84 or directly adding commits. If this were in its own repository then I could make a PR against @thegrims's fork. When he approved my PR, the commits would be added to the origin's PR. 

https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by thegrims** [comment]
That sounds good to me

**Comment by zakpatterson** [comment]
Yay!
