### ISSUE TITLE
FYI - possible testing resources

### ISSUE THREAD

**Issue by MattHJensen** [ustaxes/UsTaxes#129]
Hello, thanks for a great project. I have enjoyed watching your work. 

I am the maintainer of the [Tax-Calculator](github.com/pslmodels/tax-calculator) project. We currently [validate](https://github.com/PSLmodels/Tax-Calculator/tree/master/taxcalc/validation) against [internet TAXSIM](https://users.nber.org/~taxsim/taxsim32/). 

You might consider using these projects in your testing. 

If you would ever like to discuss cross-calculator testing or anything else, please feel free to reach out to me at my_github_username@gmail.com, or I am happy to participate in discussions in your project issues. 

Best,
Matt

**Comment by zakpatterson** [comment]
Thanks for the heads up! Your reviews of this project are always welcome. Also join our discord if you would like to chat about our respective goals with the projects!

**Comment by thegrims** [comment]
Very cool, I've heard good things about NBER
