### ISSUE TITLE
Add ARCHITECTURE.md describing high-level structure of the project

### ISSUE THREAD

**Issue by Zhomart** [ustaxes/UsTaxes#135]
Please see this article - https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html

This will be super super useful for contributors to quickly jump into contributing.

**Comment by zakpatterson** [comment]
Hey @Zhomart, I think is a great idea. I tried to kick this off by adding #138. Would you please take a look at that PR and offer your comments? As that article you linked mentions, we've been staring at this code for a while, and the input of someone fresh is super valuable. Thanks!
