### ISSUE TITLE
appimage doesn't run on fedora

### ISSUE THREAD

**Issue by nobaraos12** [ustaxes/UsTaxes#1559]
![Screenshot from 2022-12-15 18-01-57](https://user-images.githubusercontent.com/118019611/207985148-35d5283b-52cf-45fe-9367-b51e8187ac09.png)
appimage doesn't run on fedora 36

**Comment by Tater-K7S5A** [comment]
I could not get the appimage *or* the .deb to run on Linux Mint 21.1.

**Comment by m-g-m** [comment]
Same here on Linux Mint 21.3. Both deb and appimage die with the following error message:
thread 'main' panicked at 'data.len() must fit the width, height, and row_stride', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk-pixbuf-0.15.4/src/pixbuf.rs:52:13

**Comment by thegrims** [comment]
@m-g-m Looks like the issue might be related to https://github.com/tauri-apps/tauri/issues/6117 which is when there aren't the right sizes available for tauri desktop icons. I generated more icons and published a release with the new icons. When you get a chance, could you try installing the latest release and letting me know if it works for you?

**Comment by Tater-K7S5A** [comment]
Thank you!  The deb is working on Mint 21.1.
