### ISSUE TITLE
Form 8960 incorrectly includes general sales taxes paid on line 9b

### ISSUE THREAD

**Issue by grablair** [ustaxes/UsTaxes#1732]
Form 8960 (Net Investment Income Tax) allows the filer to deduct certain expenses, such as investment interest, state/local/foreign **income** tax, and other miscellaneous investment expenses before calculating the NIIT.

The instructions for line 9b from the 2022 instructions:

> ## Line 9b—State, Local, and Foreign Income Tax
> Include state, local, and foreign income taxes you paid for the tax year that are attributable to net investment income. Form 1040-NR filers include only taxes paid for the U.S. residency period of the tax year. **Sales taxes aren’t deductible in computing net investment income.** You may not take a deduction for any foreign income taxes paid for the tax year if you took a credit for any portion of them. See section 275(a)(4).

Bolded is a snippet regarding how sales taxes are not deductible in this case. 

This data is presumably filled in from Schedule A (Itemized Deductions), line 5b, and the application doesn't seem to follow the *sales* tax exclusion rule. It seems to just bring in the data directly, regardless of whether the checkbox on Schedule A, line 5b is checked, indicating an election to use the general *sales* tax deduction.

I believe this was introduced in #1696. While that change corrected the fact that the filer must itemize their taxes (and thus, their state income/sales taxes), a side effect from moving the logic away from pulling data from W2 state withholding to pulling it from Schedule A (and disregarding the general sales tax checkbox) introduced this bug.

**Comment by thegrims** [comment]
Thanks for the fix @grablair, good find!
