### ISSUE TITLE
List of supported states

### ISSUE THREAD

**Issue by kir0ul** [ustaxes/UsTaxes#1737]
Hi there,

Maybe I missed it, but I was looking for the list of supported states for the State Income Tax, is it available somewhere?

P.S. Thanks for this software, that's really needed! :pray:

**Comment by thegrims** [comment]
Hi @kir0ul only federal taxes are supported this year, so the states you should be able to file with are states without income tax

**Comment by thegrims** [comment]
Here's a list of those states https://github.com/ustaxes/UsTaxes#non-filing-states

**Comment by kir0ul** [comment]
Ok, thanks for the clarification!
