### ISSUE TITLE
Support HSA form 8889

### ISSUE THREAD

**Issue by Maximus-** [ustaxes/UsTaxes#205]
Please add support for https://www.irs.gov/forms-pubs/about-form-8889 for Health Savings Accounts :)

**Comment by zakpatterson** [comment]
Thanks @Maximus- -- are you interested in working on this? I don't have a lot of experience with HSAs, so we would need someone to come along with this need to work on it.

**Comment by Maximus-** [comment]
Hmm.. I figured you'd say that :) 

I'll see if I can find some time in the next few weeks.

**Comment by zakpatterson** [comment]
We also have a roadmap we're beginning to sketch out on the Wiki, we're trying to come up with a way to prioritize work.

**Comment by Maximus-** [comment]
Definitely sounds good; If the goals are to reach a wider audience, then it definitely makes sense to prioritize the more common forms. 80 open issues seems very optimistic, but if it's true, then that would be fantastic. Could also use a system where the open issues with the most votes get prioritized. Definitely like having one issue per schedule / form, to make it easier to track development and discussion. 

The wiki / roadmap looks very good as it stands today. :)

**Comment by zakpatterson** [comment]
Yeah the number of separate forms that could be attached to the 1040 is more than 25 and less than 50 (i think), plus 50 states, it's on the order of 80 or so distinct forms I think. Of course I'm not counting all the various incoming forms (K-1, 1099, W-2, etc) that a taxpayer receives, and I'm sure there are some states with more complex forms. https://en.wikipedia.org/wiki/IRS_tax_forms#1040.

There's no clean voting system on issues that I know of, but it is possible to sort github issues by reactions, so if people just thumbsupped the issue report then we could have live sorting based on that. Does that make sense?
