### ISSUE TITLE
Deleting your data 

### ISSUE THREAD

**Issue by robinf-scott** [ustaxes/UsTaxes#2059]
do not want to utilize  this site. want my information deleted.

**Comment by swelborn** [comment]
https://github.com/ustaxes/UsTaxes?tab=readme-ov-file#user-data

**Comment by chenyuan99** [comment]
you can clear your local storage in 
<img width="542" alt="image" src="https://github.com/user-attachments/assets/935204d4-a08f-432f-beab-3b62edebd075">
But I think it would also be a good idea for us to create a new feature to cclear out all local storage in one click @
