### ISSUE TITLE
After submitting a W2 on the wages page the 'Input data from W-2' dropdown stays open with the inputted income

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#217]
![image](https://user-images.githubusercontent.com/8848557/114110044-7114d980-988b-11eb-8e5b-16a01f0f3d3b.png)

**Comment by thegrims** [comment]
It looks like the issue is related to form elements that use a custom controller

**Comment by zakpatterson** [comment]
The same issue exists on the F1099 form and the dependent form
