### ISSUE TITLE
Tauri Source outdated

### ISSUE THREAD

**Issue by nothingismagick** [ustaxes/UsTaxes#380]
please consider updating to latest tauri source. There's been hundreds of fixes in the past month, performance enhancements (esp on windows) and overall stability.

**Comment by zakpatterson** [comment]
Hey @nothingismagick, so awesome of you to stop by! We're a little behind on dependency versions. Are you talking about our tauri dependency, or the stuff going on in `src-tauri/`? We have not customized anything in there yet.

**Comment by nothingismagick** [comment]
The tauri deps specifically in the Cargo.toml and in your package.json
