### ISSUE TITLE
Getting started switch for desktop version

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#385]
The getting started page includes buttons that say "Start return in browser", and "Download desktop version". We need to show something else for the desktop.

**Comment by zakpatterson** [comment]
Summoning @eoncarlyle, would you be interested in this as a follow on to #331? There's one other place where we test for desktop vs browser usage, [see here](https://github.com/ustaxes/UsTaxes/blob/f07ca4d3f4924915cf0076717c937f26ab1983a9/src/pdfFiller/pdfHandler.ts#L5).

**Comment by eoncarlyle** [comment]
@zakpatterson sounds good, what would make sense for the desktop version to show?

**Comment by zakpatterson** [comment]
Also, the start return in browser button currently causes a page refresh, where it should just be switching the active page. See https://github.com/ustaxes/UsTaxes/blob/master/src/components/pager.tsx#L44, where react-router's `Link` component is used instead of `href`.
