### ISSUE TITLE
Option should be removed to add spouse income when married filing separately is checked

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#416]
currently when MFS is selected income can be added from a spouse, when that income should be added to the spouse's tax return, not the one being filed

**Comment by zakpatterson** [comment]
This is an interesting one. Should selecting MFS remove income attributed to spouse? Should we output two separate returns? Should we allow income to be entered but display some kind of warning that it's removed at print time due to filing status?
