### ISSUE TITLE
Require signed commits

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#465]
Thinking about code security, from some point going forward we should require signed commits. 

https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html

This will be a little annoying for new contributors' PRs, but when a user sends a new PR, if commits are unverified, we would ask them to follow [this tutorial](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification), apply `git config --global commit.gpgsign true`, and then `git rebase master`, followed by `git commit --amend` to redo each commit on the branch, followed by force pushing.

We can add this to CONTRIBUTING as well as to a PR template.

Other projects such as Tauri require verified commits.

**Comment by thegrims** [comment]
Thanks for the link! Good thing to be aware of
