### ISSUE TITLE
Forms need to be broken down into multiple forms

### ISSUE THREAD

**Issue by bluSCALE4** [ustaxes/UsTaxes#513]
Currently, an entire page is a form and this doesn't work when we have features where you can "Add" entries. For example, if you are adding an entry and you hit enter, the submit on the main form will fire and the changes will be lost.

**Comment by zakpatterson** [comment]
`<form>`s don't nest though. So given the current dom-structure, it would be hard to implement it as separate `<form` elements with their own `onSubmit` events right?

**Comment by bluSCALE4** [comment]
`<form>`'s can't be nest but we technically are doing that. We can try wrapping sub forms with a portal to resolve the problem.

**Comment by bluSCALE4** [comment]
I gave this more thought and I suppose there are a few options. The first is to leave it as is but add validations on that force the user to enter data or maybe ask if they want to proceed without x record. 

The other option is to use portals to create sub forms. This would allow us to move code around without actually doing so. 

The other is to add enter key handlers. 

The last would be to move the code around.
