### ISSUE TITLE
Improve UX for adding records 

### ISSUE THREAD

**Issue by bluSCALE4** [ustaxes/UsTaxes#549]
Right now, when a user is adding or modifying a record, is the user hits enter or clicks next / previous, data will be lost. 

Scenario 1
Current Behavior:
User clicks add / edit
User fill out information
User presses enter
Data is lost

Expected Behavior:
User clicks add / edit
User fill out information
User presses enter
Record is saved

Scenario 2
Current Behavior:
User clicks add / edit
User fill out information
User clicks prev or next
Data is lost

Expected Behavior:
User clicks add / edit
User fill out information
User clicks prev or next
User is prompted that data will be lost if record is in dirty state.

**Comment by dbelokon** [comment]
Hello!

I managed to work on this issue, and I got a working solution for it! I will follow up with a PR shortly

**Comment by thegrims** [comment]
@dbelokon that's great! Thanks
