### ISSUE TITLE
Native Android keyboard dismissed when opened on site

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#562]
https://photos.app.goo.gl/Kx1KQkV6eNwN6AC3A

**Comment by thegrims** [comment]
https://user-images.githubusercontent.com/8848557/133351987-acae90cb-a679-4521-9a65-abd2e193049b.mp4

**Comment by zakpatterson** [comment]
The same thing is not happening on iOS, but if I click outside of a field to dismiss the keyboard, the entire form behaves like it's being selected? Not exactly sure. 
https://user-images.githubusercontent.com/1987109/133530152-31e17b0f-cc1f-453d-9714-8b56b994f5c9.MOV

**Comment by thegrims** [comment]
@zakpatterson I think this issue can be closed now, has been fixed by https://github.com/ustaxes/UsTaxes/pull/606 thoughts?
