### ISSUE TITLE
Merge contact information page into primary taxpayer page

### ISSUE THREAD

**Issue by thegrims** [ustaxes/UsTaxes#621]
- Add form fields & logic in contact information page to primary taxpayer page
- Remove contact information page
- Remove references to /contact route

**Comment by skodamarthi** [comment]
@thegrims Can I work on this?

**Comment by thegrims** [comment]
@skodamarthi yeah absolutely!

**Comment by skodamarthi** [comment]
@thegrims Raised a PR for this. Can you please check and let me know if any additional changes are needed? Thanks!
