### ISSUE TITLE
Medicare wages are not allowed to be greater than wages

### ISSUE THREAD

**Issue by dweiss2** [ustaxes/UsTaxes#880]
I have an error saying "Medicare wages are not allowed to be greater than wages" on the review and print section. This is definitely wrong because my W2 box 5 is larger than my box 1. This is allowed since anything contributing to pre-tax things like 401(k)s (box 12D). I can verify this by seeing that Box 1 + Box 12D = Box 5.

**Comment by thegrims** [comment]
This issue should be fixed now on the site! Thanks for filing an issue @dweiss2
